# BASIC

In [8]:
import pandas as pd

In [9]:
iris=pd.read_csv("Iris.csv.xls",index_col=0)
iris

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

### 1. How many samples and features are there in the Iris dataset?

In [32]:
iris.shape[0]

150

In [33]:
iris.shape[1]

5

### 2. What are the names of the features (columns) in the dataset?

In [34]:
iris.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

### 3. How many unique species of iris flowers are present in the dataset?

In [35]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### 4. What is the average sepal length for each species of iris?

In [36]:
iris['SepalLengthCm']

Id
1      5.1
2      4.9
3      4.7
4      4.6
5      5.0
      ...
146    6.7
147    6.3
148    6.5
149    6.2
150    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [37]:
iris['SepalLengthCm'].median()

5.8


### 5. What is the maximum petal width among all the iris flowers?

In [38]:
iris['PetalLengthCm'].max

<bound method NDFrame._add_numeric_operations.<locals>.max of Id
1      1.4
2      1.4
3      1.3
4      1.5
5      1.4
      ...
146    5.2
147    5.0
148    5.2
149    5.4
150    5.1
Name: PetalLengthCm, Length: 150, dtype: float64>

In [39]:
iris['PetalLengthCm'].max()

6.9

### 6. How many samples belong to each species of iris?

In [40]:
iris.value_counts('Species')

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

### 7. How many samples have a petal length greater than 5 cm?

In [41]:
iris[iris['PetalLengthCm']>5]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
84             6.0           2.7            5.1           1.6  Iris-versicolor
101            6.3           3.3            6.0           2.5   Iris-virginica
102            5.8           2.7            5.1           1.9   Iris-virginica
103            7.1           3.0            5.9           2.1   Iris-virginica
104            6.3           2.9            5.6           1.8   Iris-virginica
105            6.5           3.0            5.8           2.2   Iris-virginica
106            7.6           3.0            6.6           2.1   Iris-virginica
108            7.3           2.9            6.3           1.8   Iris-virginica
109            6.7           2.5            5.8           1.8   Iris-virginica
110            7.2           3.6            6.1           2.5   Iris-virginica
111            6.5           3.2            5.1           2.0   Iris-virginica
112            6.4           2.7            5.3           1.9   Iris-virginica
113            6.8           3.0            5.5           2.1   Iris-virginica
115            5.8           2.8            5.1           2.4   Iris-virginica
116            6.4           3.2            5.3           2.3   Iris-virginica
117            6.5           3.0            5.5           1.8   Iris-virginica
118            7.7           3.8            6.7           2.2   Iris-virginica
119            7.7           2.6            6.9           2.3   Iris-virginica
121            6.9           3.2            5.7           2.3   Iris-virginica
123            7.7           2.8            6.7           2.0   Iris-virginica
125            6.7           3.3            5.7           2.1   Iris-virginica
126            7.2           3.2            6.0           1.8   Iris-virginica
129            6.4           2.8            5.6           2.1   Iris-virginica
130            7.2           3.0            5.8           1.6   Iris-virginica
131            7.4           2.8            6.1           1.9   Iris-virginica
132            7.9           3.8            6.4           2.0   Iris-virginica
133            6.4           2.8            5.6           2.2   Iris-virginica
134            6.3           2.8            5.1           1.5   Iris-virginica
135            6.1           2.6            5.6           1.4   Iris-virginica
136            7.7           3.0            6.1           2.3   Iris-virginica
137            6.3           3.4            5.6           2.4   Iris-virginica
138            6.4           3.1            5.5           1.8   Iris-virginica
140            6.9           3.1            5.4           2.1   Iris-virginica
141            6.7           3.1            5.6           2.4   Iris-virginica
142            6.9           3.1            5.1           2.3   Iris-virginica
143            5.8           2.7            5.1           1.9   Iris-virginica
144            6.8           3.2            5.9           2.3   Iris-virginica
145            6.7           3.3            5.7           2.5   Iris-virginica
146            6.7           3.0            5.2           2.3   Iris-virginica
148            6.5           3.0            5.2           2.0   Iris-virginica
149            6.2           3.4            5.4           2.3   Iris-virginica
150            5.9           3.0            5.1           1.8   Iris-virginica

### 8. How can you filter and display only the samples belonging to a specific species, e.g., Iris setosa?

In [42]:
iris1=iris[iris['Species']=='Iris-setosa']
iris1

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
6             5.4           3.9            1.7           0.4  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa
8             5.0           3.4            1.5           0.2  Iris-setosa
9             4.4           2.9            1.4           0.2  Iris-setosa
10            4.9           3.1            1.5           0.1  Iris-setosa
11            5.4           3.7            1.5           0.2  Iris-setosa
12            4.8           3.4            1.6           0.2  Iris-setosa
13            4.8           3.0            1.4           0.1  Iris-setosa
14            4.3           3.0            1.1           0.1  Iris-setosa
15            5.8           4.0            1.2           0.2  Iris-setosa
16            5.7           4.4            1.5           0.4  Iris-setosa
17            5.4           3.9            1.3           0.4  Iris-setosa
18            5.1           3.5            1.4           0.3  Iris-setosa
19            5.7           3.8            1.7           0.3  Iris-setosa
20            5.1           3.8            1.5           0.3  Iris-setosa
21            5.4           3.4            1.7           0.2  Iris-setosa
22            5.1           3.7            1.5           0.4  Iris-setosa
23            4.6           3.6            1.0           0.2  Iris-setosa
24            5.1           3.3            1.7           0.5  Iris-setosa
25            4.8           3.4            1.9           0.2  Iris-setosa
26            5.0           3.0            1.6           0.2  Iris-setosa
27            5.0           3.4            1.6           0.4  Iris-setosa
28            5.2           3.5            1.5           0.2  Iris-setosa
29            5.2           3.4            1.4           0.2  Iris-setosa
30            4.7           3.2            1.6           0.2  Iris-setosa
31            4.8           3.1            1.6           0.2  Iris-setosa
32            5.4           3.4            1.5           0.4  Iris-setosa
33            5.2           4.1            1.5           0.1  Iris-setosa
34            5.5           4.2            1.4           0.2  Iris-setosa
35            4.9           3.1            1.5           0.1  Iris-setosa
36            5.0           3.2            1.2           0.2  Iris-setosa
37            5.5           3.5            1.3           0.2  Iris-setosa
38            4.9           3.1            1.5           0.1  Iris-setosa
39            4.4           3.0            1.3           0.2  Iris-setosa
40            5.1           3.4            1.5           0.2  Iris-setosa
41            5.0           3.5            1.3           0.3  Iris-setosa
42            4.5           2.3            1.3           0.3  Iris-setosa
43            4.4           3.2            1.3           0.2  Iris-setosa
44            5.0           3.5            1.6           0.6  Iris-setosa
45            5.1           3.8            1.9           0.4  Iris-setosa
46            4.8           3.0            1.4           0.3  Iris-setosa
47            5.1           3.8            1.6           0.2  Iris-setosa
48            4.6           3.2            1.4           0.2  Iris-setosa
49            5.3           3.7            1.5           0.2  Iris-setosa
50            5.0           3.3            1.4           0.2  Iris-setosa

In [43]:
iris2=iris[iris['Species']=='Iris-versicolor']
iris2

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
51             7.0           3.2            4.7           1.4  Iris-versicolor
52             6.4           3.2            4.5           1.5  Iris-versicolor
53             6.9           3.1            4.9           1.5  Iris-versicolor
54             5.5           2.3            4.0           1.3  Iris-versicolor
55             6.5           2.8            4.6           1.5  Iris-versicolor
56             5.7           2.8            4.5           1.3  Iris-versicolor
57             6.3           3.3            4.7           1.6  Iris-versicolor
58             4.9           2.4            3.3           1.0  Iris-versicolor
59             6.6           2.9            4.6           1.3  Iris-versicolor
60             5.2           2.7            3.9           1.4  Iris-versicolor
61             5.0           2.0            3.5           1.0  Iris-versicolor
62             5.9           3.0            4.2           1.5  Iris-versicolor
63             6.0           2.2            4.0           1.0  Iris-versicolor
64             6.1           2.9            4.7           1.4  Iris-versicolor
65             5.6           2.9            3.6           1.3  Iris-versicolor
66             6.7           3.1            4.4           1.4  Iris-versicolor
67             5.6           3.0            4.5           1.5  Iris-versicolor
68             5.8           2.7            4.1           1.0  Iris-versicolor
69             6.2           2.2            4.5           1.5  Iris-versicolor
70             5.6           2.5            3.9           1.1  Iris-versicolor
71             5.9           3.2            4.8           1.8  Iris-versicolor
72             6.1           2.8            4.0           1.3  Iris-versicolor
73             6.3           2.5            4.9           1.5  Iris-versicolor
74             6.1           2.8            4.7           1.2  Iris-versicolor
75             6.4           2.9            4.3           1.3  Iris-versicolor
76             6.6           3.0            4.4           1.4  Iris-versicolor
77             6.8           2.8            4.8           1.4  Iris-versicolor
78             6.7           3.0            5.0           1.7  Iris-versicolor
79             6.0           2.9            4.5           1.5  Iris-versicolor
80             5.7           2.6            3.5           1.0  Iris-versicolor
81             5.5           2.4            3.8           1.1  Iris-versicolor
82             5.5           2.4            3.7           1.0  Iris-versicolor
83             5.8           2.7            3.9           1.2  Iris-versicolor
84             6.0           2.7            5.1           1.6  Iris-versicolor
85             5.4           3.0            4.5           1.5  Iris-versicolor
86             6.0           3.4            4.5           1.6  Iris-versicolor
87             6.7           3.1            4.7           1.5  Iris-versicolor
88             6.3           2.3            4.4           1.3  Iris-versicolor
89             5.6           3.0            4.1           1.3  Iris-versicolor
90             5.5           2.5            4.0           1.3  Iris-versicolor
91             5.5           2.6            4.4           1.2  Iris-versicolor
92             6.1           3.0            4.6           1.4  Iris-versicolor
93             5.8           2.6            4.0           1.2  Iris-versicolor
94             5.0           2.3            3.3           1.0  Iris-versicolor
95             5.6           2.7            4.2           1.3  Iris-versicolor
96             5.7           3.0            4.2           1.2  Iris-versicolor
97             5.7           2.9            4.2           1.3  Iris-versicolor
98             6.2           2.9            4.3           1.3  Iris-versicolor
99             5.1           2.5            3.0           1.1  Iris-versicolor
100            5.7           2.8            4.1           1.3  Iris-versicolor

In [44]:
iris3=iris[iris['Species']=='Iris-virginica']
iris3

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
101            6.3           3.3            6.0           2.5  Iris-virginica
102            5.8           2.7            5.1           1.9  Iris-virginica
103            7.1           3.0            5.9           2.1  Iris-virginica
104            6.3           2.9            5.6           1.8  Iris-virginica
105            6.5           3.0            5.8           2.2  Iris-virginica
106            7.6           3.0            6.6           2.1  Iris-virginica
107            4.9           2.5            4.5           1.7  Iris-virginica
108            7.3           2.9            6.3           1.8  Iris-virginica
109            6.7           2.5            5.8           1.8  Iris-virginica
110            7.2           3.6            6.1           2.5  Iris-virginica
111            6.5           3.2            5.1           2.0  Iris-virginica
112            6.4           2.7            5.3           1.9  Iris-virginica
113            6.8           3.0            5.5           2.1  Iris-virginica
114            5.7           2.5            5.0           2.0  Iris-virginica
115            5.8           2.8            5.1           2.4  Iris-virginica
116            6.4           3.2            5.3           2.3  Iris-virginica
117            6.5           3.0            5.5           1.8  Iris-virginica
118            7.7           3.8            6.7           2.2  Iris-virginica
119            7.7           2.6            6.9           2.3  Iris-virginica
120            6.0           2.2            5.0           1.5  Iris-virginica
121            6.9           3.2            5.7           2.3  Iris-virginica
122            5.6           2.8            4.9           2.0  Iris-virginica
123            7.7           2.8            6.7           2.0  Iris-virginica
124            6.3           2.7            4.9           1.8  Iris-virginica
125            6.7           3.3            5.7           2.1  Iris-virginica
126            7.2           3.2            6.0           1.8  Iris-virginica
127            6.2           2.8            4.8           1.8  Iris-virginica
128            6.1           3.0            4.9           1.8  Iris-virginica
129            6.4           2.8            5.6           2.1  Iris-virginica
130            7.2           3.0            5.8           1.6  Iris-virginica
131            7.4           2.8            6.1           1.9  Iris-virginica
132            7.9           3.8            6.4           2.0  Iris-virginica
133            6.4           2.8            5.6           2.2  Iris-virginica
134            6.3           2.8            5.1           1.5  Iris-virginica
135            6.1           2.6            5.6           1.4  Iris-virginica
136            7.7           3.0            6.1           2.3  Iris-virginica
137            6.3           3.4            5.6           2.4  Iris-virginica
138            6.4           3.1            5.5           1.8  Iris-virginica
139            6.0           3.0            4.8           1.8  Iris-virginica
140            6.9           3.1            5.4           2.1  Iris-virginica
141            6.7           3.1            5.6           2.4  Iris-virginica
142            6.9           3.1            5.1           2.3  Iris-virginica
143            5.8           2.7            5.1           1.9  Iris-virginica
144            6.8           3.2            5.9           2.3  Iris-virginica
145            6.7           3.3            5.7           2.5  Iris-virginica
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

### 9. What is the minimum and maximum sepal length among Iris setosa flowers?

In [45]:
iris1['SepalLengthCm'].min()

4.3

In [46]:
iris1['SepalLengthCm'].max()

5.8

### 10. How many missing values are there in each column of the dataset?

In [57]:
iris['SepalLengthCm'].isnull().sum()

0

In [58]:
iris['SepalWidthCm'].isnull().sum()

0

In [59]:
iris['PetalLengthCm'].isnull().sum()

0

In [60]:
iris['PetalWidthCm'].isnull().sum()

0

In [61]:
iris['Species'].isnull().sum()

0

### 11. Create a new DataFrame containing only the samples with petal length greater than 4.5 cm.

In [19]:
iris.loc[(iris['PetalLengthCm']>4.5)]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
51             7.0           3.2            4.7           1.4  Iris-versicolor
53             6.9           3.1            4.9           1.5  Iris-versicolor
55             6.5           2.8            4.6           1.5  Iris-versicolor
57             6.3           3.3            4.7           1.6  Iris-versicolor
59             6.6           2.9            4.6           1.3  Iris-versicolor
..             ...           ...            ...           ...              ...
146            6.7           3.0            5.2           2.3   Iris-virginica
147            6.3           2.5            5.0           1.9   Iris-virginica
148            6.5           3.0            5.2           2.0   Iris-virginica
149            6.2           3.4            5.4           2.3   Iris-virginica
150            5.9           3.0            5.1           1.8   Iris-virginica

[63 rows x 5 columns]

### 12. Which species of iris has the highest average petal width?

In [27]:
species_grp=iris.groupby("Species")
species_grp['PetalWidthCm'].mean()

Species
Iris-setosa        0.244
Iris-versicolor    1.326
Iris-virginica     2.026
Name: PetalWidthCm, dtype: float64

### 13. Use the apply function to convert all petal lengths from centimeters to millimeters.

In [10]:
def milli(x):
    return(x*10)

In [9]:
iris.apply(milli'PetalLengthCm')

Id
1      1.4
2      1.4
3      1.3
4      1.5
5      1.4
      ...
146    5.2
147    5.0
148    5.2
149    5.4
150    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

### 14. Replace the species names in the Iris dataset with numeric labels as follows: "Iris setosa" with 0, "Iris versicolor" with 1, and "Iris virginica" with 2.

In [12]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [17]:
num=iris.replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})
num

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3        2
147            6.3           2.5            5.0           1.9        2
148            6.5           3.0            5.2           2.0        2
149            6.2           3.4            5.4           2.3        2
150            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

### 15. Create a new column named "species_type" in the Iris dataset that maps the species names to specific types based on their initial letters. Use "S" for species starting with 'Iris setosa', "V" for species starting with 'Iris versicolor', and "G" for species starting with 'Iris virginica'

In [27]:
iris.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [28]:
Species=iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm','Species']]

In [29]:
species_type=iris["Species"].map({'Iris-setosa':'S','Iris-versicolor':'V','Iris-virginica':'G'})
species_type

Id
1      S
2      S
3      S
4      S
5      S
      ..
146    G
147    G
148    G
149    G
150    G
Name: Species, Length: 150, dtype: object

In [31]:
iris_add=pd.concat([Species,species_type],axis='columns')
iris_add

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species
Id,,,,,,
1,5.1,3.5,1.4,0.2,Iris-setosa,S
2,4.9,3.0,1.4,0.2,Iris-setosa,S
3,4.7,3.2,1.3,0.2,Iris-setosa,S
4,4.6,3.1,1.5,0.2,Iris-setosa,S
5,5.0,3.6,1.4,0.2,Iris-setosa,S
...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,Iris-virginica,G
147,6.3,2.5,5.0,1.9,Iris-virginica,G
148,6.5,3.0,5.2,2.0,Iris-virginica,G
149,6.2,3.4,5.4,2.3,Iris-virginica,G
150,5.9,3.0,5.1,1.8,Iris-virginica,G

# Advanced

### 1. Create a new column named "sepal_length_category" that maps the sepal length to categories as follows: "Short" for sepal length less than 5.5 cm, "Medium" for sepal length between 5.5 cm and 6.5 cm (inclusive), and "Long" for sepal length greater than 6.5 cm.

In [10]:
sepal=iris['SepalLengthCm'].unique()
sepal

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [11]:
Species=iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm','Species']]

In [13]:
sepal_length_category=iris['SepalLengthCm'].map({"Short": lambda x: x < 5.5,
                                                 'Medium': lambda x: 5.5 >= x <= 6.5,
                                                 "Long": lambda x: x > 6.5})
sepal_length_category

Id
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
      ...
146    NaN
147    NaN
148    NaN
149    NaN
150    NaN
Name: SepalLengthCm, Length: 150, dtype: object

In [69]:
add=pd.concat([Species,sepal_length_category],axis='columns')
add

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SepalLengthCm
Id,,,,,,
1,5.1,3.5,1.4,0.2,Iris-setosa,NaN
2,4.9,3.0,1.4,0.2,Iris-setosa,NaN
3,4.7,3.2,1.3,0.2,Iris-setosa,NaN
4,4.6,3.1,1.5,0.2,Iris-setosa,NaN
5,5.0,3.6,1.4,0.2,Iris-setosa,NaN
...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,Iris-virginica,NaN
147,6.3,2.5,5.0,1.9,Iris-virginica,NaN
148,6.5,3.0,5.2,2.0,Iris-virginica,NaN
149,6.2,3.4,5.4,2.3,Iris-virginica,NaN
150,5.9,3.0,5.1,1.8,Iris-virginica,NaN

NameError: name 'add' is not defined

### 2. Use the map() function to replace the values in the "species" column with their corresponding full species names, e.g., 0 with "Iris setosa", 1 with "Iris versicolor", and 2 with "Iris virginica".

### 3. Create a new column named "petal_length_label" that maps the petal length values to "Short", "Medium", or "Long" based on the quartiles of the petal length distribution (e.g., below 25th percentile: "Short", between 25th and 75th percentile: "Medium", above 75th percentile: "Long")

### 4. Map the sepal width values to "Narrow" if they are less than 3.0 cm, and "Wide" if they are 3.0 cm or greater. Create a new column named "sepal_width_type" to store this information.

### 5. Use the map() function to convert the "species" column to lowercase, so all species names are in lowercase letters.

### 6. Map the "petal_area" values to "Small", "Medium", or "Large" based on custom thresholds (e.g., below 2.5 cm^2: "Small", between 2.5 cm^2 and 5.0 cm^2: "Medium", above 5.0 cm^2: "Large").

### 7. Create a new column named "species_encoded" that maps the species names to unique integer values, where "Iris setosa" is encoded as 0, "Iris versicolor" as 1, and "Iris virginica" as 2.

### 8. Map the "sepal_length" values to the corresponding category labels "Very Short", "Short", "Medium", "Long", and "Very Long" based on custom-defined bins.

### 9. Use the map() function to replace the "species_type" values with their corresponding full names, e.g., "S" with "Iris setosa", "V" with "Iris versicolor", and "G" with "Iris virginica".

### 10. Create a new column named "petal_width_type" that maps the petal width values to "Narrow", "Medium", or "Wide" based on custom-defined bins

# Advanced(Titanic Dataset)

In [1]:
import pandas as pd

In [2]:
titanic=pd.read_csv('Titanic-Dataset.xls',index_col=0)
titanic

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 1. What was the overall survival rate of passengers on the Titanic?

In [48]:
titanic['Survived'].value_counts(1)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [5]:
titanic['Survived'].mean()

0.3838383838383838

In [53]:
titanic['Survived'].value_counts(normalize=True)*100

0    61.616162
1    38.383838
Name: Survived, dtype: float64

### 2. What was the survival rate for male and female passengers separately?

In [18]:
gender_grp=titanic.groupby('Sex')
gender_grp.get_group('female')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [23]:
gender_grp['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [55]:
gender_grp['Survived'].value_counts(1)

Sex     Survived
female  1           0.742038
        0           0.257962
male    0           0.811092
        1           0.188908
Name: Survived, dtype: float64

### 3. How many passengers survived in each passenger class (1st, 2nd, and 3rd class)?

In [35]:
psngr_sur=titanic.groupby('Pclass')
psngr_sur['Survived'].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

### 4. What was the average age of survivors and non-survivors?

In [6]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
avrg=titanic.groupby('Survived')
avrg['Age'].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

### 5. Did the passenger class have any impact on the survival rate? Compare survival rates for each class.

In [65]:
titan=titanic.groupby('Pclass')
titan['Survived'].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: Survived, dtype: int64

In [66]:
titan['Survived'].value_counts(1)

Pclass  Survived
1       1           0.629630
        0           0.370370
2       0           0.527174
        1           0.472826
3       0           0.757637
        1           0.242363
Name: Survived, dtype: float64

### 6. How many passengers had siblings/spouses aboard? Did having siblings/spouses increase the chances of survival?

In [6]:
board=titanic['SibSp'].value_counts()
board

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

NameError: name 'board' is not defined

In [34]:
sibsp=board['SibSp']
sibsp.value_counts()

PassengerId  SibSp
1            1        1
2            1        1
3            0        1
4            1        1
5            0        1
                     ..
887          0        1
888          0        1
889          1        1
890          0        1
891          0        1
Name: SibSp, Length: 891, dtype: int64

### 7. How many passengers had parents/children aboard? Did having parents/children increase the chances of survival?

### 8. Did the port of embarkation affect the survival rate? Compare survival rates for each embarkation port (C - Cherbourg, Q - Queenstown, S - Southampton).

### 9. Is there any correlation between fare paid and survival rate?